# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedembeds',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='author_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='author_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='thumbnail_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='thumbnail_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
